### ISSUE TITLE
Wrong file name in examples

### ISSUE THREAD

**Issue by imilos** [tmrdja/BlackFoxPython#1]
[milos@mmilos examples]$ python3 test_train_keras.py 
Traceback (most recent call last):
  File "test_train_keras.py", line 66, in <module>
    'data/trained_network_cancer.onnx'
  File "/home/milos/.local/lib/python3.6/site-packages/blackfox/black_fox.py", line 91, in train_keras
    config.dataset_id = self.upload_data_set(data_set_path)
  File "/home/milos/.local/lib/python3.6/site-packages/blackfox/black_fox.py", line 43, in upload_data_set
    id = self.sha1(path)
  File "/home/milos/.local/lib/python3.6/site-packages/blackfox/black_fox.py", line 301, in sha1
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/cancer_train_set.csv'

**Comment by tmrdja** [comment]
This is corrected
